name: VSIX

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install VSCE
        run: sudo yarn global add vsce

      - name: Package VSIX
        run: |
          yarn install
          vsce package --yarn -o vs-code-modal.vsix

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: npm-logs
          path: /home/runner/.npm/_logs

      - uses: actions/upload-artifact@v1
        with:
          name: vs-code-modal.vsix
          path: vs-code-modal.vsix
